version: '3.8'

networks:
  bank_service:
    name: bank_service

services:
  nginx:
    networks:
      - bank_service
    image: openresty/openresty:alpine-fat #for install nginx with lua
    ports:
      - "8080:8080"
    volumes:
      - ./nginx.conf:/usr/local/openresty/nginx/conf/nginx.conf
    command: /bin/sh -c "luarocks install lua-resty-http && /usr/local/openresty/bin/openresty -g 'daemon off;'" #install lua and start nginx
    depends_on:
      - init-kafka

  init-kafka:  #creating topic
    networks:
      - bank_service
    image: confluentinc/cp-kafka:7.6.0
    restart: on-failure #wait for kafka start
    entrypoint: [ '/bin/sh', '-c' ]
    command: |
      "
      # kafka-topics --bootstrap-server localhost:9092   --create --if-not-exists --topic userID
      # kafka-topics --bootstrap-server kafka:29092 --list 
      
      kafka-topics --bootstrap-server kafka:29092   --create --if-not-exists --topic userID 
      "
    depends_on:
      - kafka

  # reachable on 9092 from the host and on 29092 from inside docker compose
  kafka:
    networks:
      - bank_service
    image: confluentinc/cp-kafka:7.6.0
    ports:
      - "9092:9092"
    expose:
      - "29092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
    depends_on:
      - zookeeper

  zookeeper:
    networks:
      - bank_service
    image: confluentinc/cp-zookeeper:latest
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181


