version: "3.8"

networks: #connect to external network-to us–∞ kafka
  bank_service:
    external: true


services:
  auth_service:
    networks:
      - bank_service
    build: ./
    ports:
      - "8082:8082"
    depends_on:
      - grpc_gateway

  grpc_gateway:
    networks:
      - bank_service
    build: ./
    ports:
      - "8083:8083"
    depends_on:
      - migrate

  migrate:
    networks:
      - bank_service
    image: migrate/migrate:latest
    volumes:
      - ./database/migrations:/migrations
    command: ["-path", "/migrations", "-database", "postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${HOST}:${PORT}/${DBNAME}?sslmode=${SSLMODE}", "up"]
    restart: on-failure #wait for db start
    env_file:
    - .env
    depends_on:
      - postgres

  postgres:
    networks:
      - bank_service
    image:
      postgres:16.2
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
    ports:
      - "5432:5432"


