apiVersion: apps/v1 #версия кубера для деплоя и тд
kind: Deployment #управляет созданием и обновлением подов(1 ли неск.контейнеров с общим запуском и хранилищем)
metadata:
  name: credit-service-deployment #имя общего кластера,в котором будут поды и контейнеры
spec:
  replicas: 2 #наш сервер запускается в 1 кластере.В котором уже находятся поды с контейнерами.Поэтому если кластер падает=все рушится,нужна реплика для откзоустойчивости.
  selector:
    matchLabels: #конкретные лейблы, которые ресурс должен иметь, чтобы быть выбранным-в нашем случае под.
      app: credit-service #метка ,по которой будут искаться поды с такой же меткой
  template:
    metadata:
      labels:
        app: credit-service #метка,на основе кот.этот под будет выбран
    spec:
      containers:
        - name: credit-service-container
          image: flaw1ess/bank_credit_service:latest
          ports:
            - containerPort: 8080
        - name: mongodb-container
          image: mongo:latest
          ports:
            - containerPort: 27017
