apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: credit-service
  annotations:
    kubernetes.io/ingress.class: "nginx"
  labels:
    app: credit-service
spec:
  rules:
    - host: localhost
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: credit-service
                port:
                  name: credit-service
