name: bank_service

on:
  push:
    branches:
      - main

jobs:
  golangci_credit_service:
    name: lint_credit_service
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.21.4'
          cache: false
      - name: golangci-lint for credit_service
        uses: golangci/golangci-lint-action@v4
        with:
          version: v1.54
          working-directory: credit_service
          args: --config .golangci.yml

  golangci_auth_service:
    name: lint_auth_service
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.21.4'
          cache: false
      - name: golangci-lint for auth_service
        uses: golangci/golangci-lint-action@v4
        with:
          version: v1.54
          working-directory: auth_service
          args: --config .golangci.yml


  check_changes:
    runs-on: ubuntu-latest
    outputs:
      auth_service: ${{ steps.check_files.outputs.auth_service }}
      credit_service: ${{ steps.check_files.outputs.credit_service }}
    steps:
      - name: Checkout main
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Check for changes in services
        id: check_files
        run: |
          echo "=============== list modified files ==============="
          git diff --name-only HEAD^ HEAD
          
          echo "========== check paths of modified files =========="        
          git diff --name-only HEAD^ HEAD > files.txt
          while IFS= read -r file; do
            echo $file
            if [[ $file == auth_service/* ]]; then
              echo "auth_service=true" >> $GITHUB_OUTPUT
            elif [[ $file == credit_service/* ]]; then
              echo "credit_service=true" >> $GITHUB_OUTPUT
            fi
          done < files.txt
 

  auth_service:
    needs: check_changes
    if: ${{ needs.check_changes.outputs.auth_service == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v4

      - name: Set up Go 1.21.4
        uses: actions/setup-go@v5
        with:
          go-version: 1.21.4

      - name: Tests
        run: | 
          cd auth_service
          go test ./...

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ./auth_service
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/bank_auth_service:latest

  credit_service:
    needs: check_changes
    if: ${{ needs.check_changes.outputs.credit_service == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v4

      - name: Set up Go 1.21.4
        uses: actions/setup-go@v5
        with:
          go-version: 1.21.4

      - name: Tests
        run: |
          cd credit_service
          go test ./...

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ./credit_service
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/bank_credit_service:latest



